# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question',
        ),
    ]
