# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20170721_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questioned_at',
        ),
    ]
