# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_extraanswer_extraquestion_requied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='extraanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtraQuestion',
        ),
        migrations.RemoveField(
            model_name='requied',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtraAnswer',
        ),
        migrations.DeleteModel(
            name='Requied',
        ),
    ]
