# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20170717_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='photo',
            field=models.FileField(default='1.jpg', upload_to='photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
