# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20170724_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='photo',
        ),
    ]
