# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_remove_answer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='day',
            field=models.CharField(default=1, max_length=2, verbose_name='월'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='month',
            field=models.CharField(default='1', max_length=2, verbose_name='달'),
            preserve_default=False,
        ),
    ]
