# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0008_auto_20170726_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=32),
        ),
    ]
