# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0009_auto_20170803_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=128),
        ),
    ]
