# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170729_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='before make', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='010-1234-1234', max_length=20, validators=[django.core.validators.RegexValidator('^010[1-9]\\d{7}$')]),
            preserve_default=False,
        ),
    ]
