# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170801_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='xx시 xx구'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='01012341234', max_length=20, validators=[django.core.validators.RegexValidator('^010[1-9]\\d{7}$')], verbose_name='01012341234'),
            preserve_default=False,
        ),
    ]
