# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170801_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ok_answer',
            field=models.BooleanField(default=False),
        ),
    ]
