# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_ok_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ok_answer',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='010-1234-1234', max_length=20, validators=[django.core.validators.RegexValidator('^010[1-9]\\d{7}$')]),
            preserve_default=False,
        ),
    ]
