# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 22:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170805_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
