# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 23:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170805_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.EmailField(max_length=20),
        ),
    ]
