# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170805_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=' ', upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^010[1-9]\\d{7}$')]),
        ),
    ]
