# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:29
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170806_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
