# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exqna', '0001_initial'),
    ]

