# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exqna', '0002_auto_20170719_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
