# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exqna', '0003_auto_20170813_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraquestion',
            name='questioned_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
